apiVersion: v1
kind: Service
metadata:
  name: odlux
  namespace: nonrtric
  labels:
    run: odlux
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    nodePort: 31766
  selector:
    run: odlux
