apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-mountpoint-registrar.properties
  namespace: nonrtric

data:
{{ (.Files.Glob "config/mountpoint-registrar.properties").AsConfig | nindent 2 }}
