################################################################################
#   Copyright (c) 2023 Nordix Foundation.                                      #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nonrtricgateway
  namespace: nonrtric
  labels:
    app: nonrtric-nonrtricgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonrtric-nonrtricgateway
  template:
    metadata:
      labels:
        app: nonrtric-nonrtricgateway
    spec:
      containers:
      - name: nonrtric-nonrtricgateway
        image: "{{ .Values.nonrtricgateway.image.registry }}/{{ .Values.nonrtricgateway.image.name }}:{{ .Values.nonrtricgateway.image.tag }}"
        imagePullPolicy: {{ .Values.nonrtricgateway.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.nonrtricgateway.service.targetPort1 }}
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: {{ .Values.nonrtricgateway.service.targetPort1 }}
          initialDelaySeconds: {{ .Values.nonrtricgateway.readiness.initialDelaySeconds }} # changed from liveness
          periodSeconds: {{ .Values.nonrtricgateway.readiness.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.nonrtricgateway.service.targetPort1 }}
          initialDelaySeconds: {{ .Values.nonrtricgateway.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.nonrtricgateway.liveness.periodSeconds }}
        volumeMounts:
        - name: nonrtricgateway-config
          mountPath: /opt/app/nonrtric-gateway/config
      volumes:
        - name: nonrtricgateway-config
          configMap:
            name: nonrtricgateway-configmap
