#  ============LICENSE_START===============================================
#  Copyright (C) 2023 Nordix Foundation. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#

apiVersion: v1
kind: Pod
metadata:
  name: rapps
  namespace: nonrtric
  labels:
    app: rapps
spec:
  containers:
  - name: pm-rapp
    image: {{ .Values.global.extimagerepo }}pm-rapp:latest
    {{- if .Values.global.extimagerepo }}
    imagePullPolicy: Always
    {{- else }}
    imagePullPolicy: Never
    {{- end }}
    ports:
    - name: http
      containerPort: 80
    env:
    - name: APPID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: APPNS
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: KAFKA_SERVER
      value: kafka-1-kafka-bootstrap.nonrtric:9097
    - name: ICS
      value: informationservice.nonrtric:8083
    - name: TOPIC
      value: rapp-topic
    # Set value to any string to log payload
    - name: LOG_PAYLOAD
      value: '1'
    # Set value to any string to indicate that payload is gzipped
    - name: GZIP
      value: ''
    - name: CREDS_GRANT_TYPE
      value: client_credentials
    - name: CREDS_CLIENT_SECRET
      value: {{ .Values.pmrapp.clientsecret }}
    - name: CREDS_CLIENT_ID
      value: pm-rapp
    - name: AUTH_SERVICE_URL
      value: http://keycloak.nonrtric:8080/realms/nonrtric-realm/protocol/openid-connect/token
    volumeMounts:
    - mountPath: /config
      name: pm-rapp-jobdef
    - mountPath: /output/prb_usage_reports
      name: shared-data

  - name: es-rapp
    image: {{ .Values.global.extimagerepo }}es-rapp:latest
    {{- if .Values.global.extimagerepo }}
    imagePullPolicy: Always
    {{- else }}
    imagePullPolicy: Never
    {{- end }}
    env:
    - name: SDN_CONTROLLER_ADDRESS
      value: "172.17.0.1"
    - name: SDN_CONTROLLER_PORT
      value: "80"
    - name: SDN_CONTROLLER_USERNAME
      value: "root"
    - name: SDN_CONTROLLER_PASSWORD
      value: "viavi"
    - name: A1T_ADDRESS
      value: "onos-a1t.riab"
    - name: A1T_PORT
      value: "9639"
    - name: RANSIM_DATA_PATH
      value: /input/prb_usage_reports
    - name: LOAD_PREDICTOR
      value: "172.20.14.129"
    - name: LOAD_PREDICTOR_PORT
      value: "9008"
    - name: LOAD_PREDICTOR_API
      value: "predict"
    volumeMounts:
    - mountPath: /input/prb_usage_reports
      name: shared-data

  volumes:
  - configMap:
      name: pm-rapp-jobdef
    name: pm-rapp-jobdef
  - name: shared-data
    emptyDir: {}
