''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' 
' Copyright 2023 Open Networking Foundation
' This work is licensed under a Creative Commons Attribution 4.0 International License.
' SPDX-License-Identifier: CC-BY-4.0
' https://creativecommons.org/licenses/by/4.0/deed.en

@startuml deployment

package "nonrtric" {
    node "Non-RT RIC"{
        component "data-file-collector" as dfc
        component "pm-converter" as pmc
        component "pm-producer" as pmp
        component "kafka" as kafka
        component "ES rApp" as rapp #LightCoral
    }
    node "SMO" {
        component "ves-collector" as ves
        component "message-router" as mr
        database "persistence" as sdnrdb
        component "controller" as controller
        component "odlux" as gui
    }
}

package "riab" {
    node "RAN-Simulator" {
        interface E2
        component "O-DU" as odu
        collections "UEs"
        E2 -- odu
    }
    node "Near-RT RIC" {
        interface A1
        component "onos-a1t" as a1t
        component "onos-cli"
        component "onos-topo"
        component "onos-e2t"
        component "onos-config"
        component "TS xApp" #LightCoral
        A1 -- a1t
    }
}

package "ran" as ran_ns{
    
    node "O1 Simulator"{
        interface O1
        component "ntsim-odu" as odu_o1
        O1 -- odu_o1
    }
}



' End Diagram
' Format
right footer <img:https://opennetworking.org/wp-content/uploads/2020/12/ONF_NO-TAG_WITH-GRADIENT.png{scale=0.2}> \lCopyright 2023 Open Networking Foundation.\lThis work is licensed under a Creative Commons Attribution 4.0\l International License.\lSPDX-License-Identifier: CC-BY-4.0\n2023-09-06 | Thanks to PlantUML!

skinparam backgroundColor #fefefe
'skinparam handwritten true
skinparam roundcorner 15

@enduml
